name: DelphiTestPlugin
version: "1.0.0"
main: "com.juliewoolie.delphitest.DelphiTestPlugin"
api-version: "1.21"

dependencies:
  server:
    Delphi:
      load: BEFORE
      required: true
      join-classpath: true